package com.java.oopscodings;

/*super() constructor will be generated by compiler
in all child class constructor*/


class SuperClass
{
	SuperClass(){
		System.out.println("super class instance block");
	}
}
public class ConstructorSuperClassCalling extends SuperClass {

	ConstructorSuperClassCalling()
	{
		super();
		System.out.println("0-args constructor");
	}
	ConstructorSuperClassCalling(int a)
	{
		System.out.println("1-args constructor");
	}
	public static void main(String [] args)
	{
		new ConstructorSuperClassCalling();
		new ConstructorSuperClassCalling(2);
	}
}
